package org.rcsb.genevariation.mappers;

import org.biojava.nbio.structure.Chain;
import org.biojava.nbio.structure.Structure;
import org.junit.Test;
import org.rcsb.correlatedexons.utils.StructureUtils;

/**
 * Created by yana on 4/21/17.
 */
public class TestUniprotToHomologyMapper {

    @Test
    public void testMapping() throws Exception {

        //SwissModel API: https://swissmodel.expasy.org/repository/uniprot/O94856.json?provider=swissmodel

        String[] alignment = {"TQPPTITKQSAKDHIVDPRDNILIECEAKGNPAPSFHWTR-NSRFFNIAKDPRVSMRRRSGTLVIDFRSG--GRPEEYEGEYQCFARNKFGTALSNRIRLQVSKSPLWPKENLDPVVVQEGAPLTLQCNPPPGLPS--PVIFWMSSSMEPIT----QDKRVSQGHNGDLYFSNVMLQDM-QTDYSCNARFHFTHTIQQK-NPFTLKVLTTRGVAERTPSFMYPQGTASSQMVLRGMDLLLECIASGVPTPDIAWYKKGGDLPSDK-----AKFENFNKALRITNVSEEDSGEYFCLASNKMGSIRHTISVRVKAAPYWLDEPKNLILAPGEDGRLVCRANGNPKPTVQWMVNGEPLQSAPPNPNREVAGDTIIFRDTQISSRAVYQCNTSNEHGYLLANAFVSVL--DVPPRMLSPRNQLIRVILYNRTRLDCPFFGSPIPTLRWFKNGQGSNLDGGNYHV----YENG----SLEIKMIRKEDQGIYTCVATNILGKAENQVRLEVKDPTRIYRMPEDQVARRGTTVQLECRVKHDPSLKLTVSWLKDDEPLYIGNRMKK-EDDSLTIFGVA-ERDQGSYTCVASTELD-QDLAKAYLTVLADQATPTNRLAALPKGRPDRPRDLELTDLAERSVRLTWIPGDANNSPITDYVVQFEEDQF--QPGVWHDHS-KYPGSVNSAVLRLSPYVNYQFRVIAINEVGSSHPSLPSERYRTSGAPPESNPGDVKGEGTRK----------NNMEITWTPMNATSAFGPNLRYIVKWRRRETREAWNNVTVWGSRYVVGQTPVYVPYEIRVQAENDFGKGPE",
                              "QKGPVFLKEPTNRIDFSNSTGAEIECKASGNPMPEIIWIRSDGTAVGDV--PGLRQISSDGKLVFPPFRAEDYRQEVHAQVYACLARNQFGSIISRDVHVRAVVAQYYE-ADVNKEHVIRGNSAVIKCLIPSFVADFVEVVSWHTDEEENYFPGAEYDGKYLVLPSGELHIREVGPEDGYKS-YQCRTKHRLTGETRLSATKGRLVITE--PISSAVPKVVSL-AKFDMKTYSGSSTMALLCPAQGYPVPVFRWYKFIEGTTRKQAVVLNDRVKQVSGTLIIKDAVVEDSGKYLCVVNNSVGGESVETVLTVTAPLSAKIDPPTQTVDFGRPAVFTCQYTGNPIKTVSWMKDGKAIGH---------SESVLRIESVKKEDKGMYQCFVRNDRESAEASAELKLGGRFDPPVIRQAFQ-EETMEPGPSVFLKCVAGGNPTPEISWELDGKKIAN-NDRYQVGQYVTVNGDVVSYLNITSVHANDGGLYKCIAKSKVGVAEHSAKLNVYGLPYI-RQMEKKAIVAGETLIVTCPVAGYPI--DSIVWERDNRALPINRKQKVFPNGTLIIENVERNSDQATYTCVAKNQEGYSARGSLEVQVMVLPRIIP-----------FAFEEG--PAQVGQYLTLHCSVPGG-DLP---LNIDWTLDGQAISEDLGITTSRVGRRGSVLTIEAVEASHAGNFTCHARNLAGHQQFTTPLNV-YVPPR-WILEPTDKAFAQGSDAKVECKADGFPKPQVTWKKAV-----GDTPGEYKDLKK---S---DNIRVEEGTLHVDNIQKTNEGYYLCEAINGIGSGLS"};

        Structure structure = StructureUtils.getModelStructure("https://swissmodel.expasy.org/repository/uniprot/O94856.pdb?range=38-812&template=3dmk.1.A&provider=swissmodel");
        Chain chain = structure.getChainByIndex(0);

        int from = 38; int start = 626; int end = 660; int to = 812;

        System.out.println();
    }

}
