package org.rcsb.genevariation.mappers;

import org.junit.Test;

import static org.junit.Assert.assertEquals;

/**
 * Created by yana on 4/21/17.
 */
public class TestUniprotToHomologyMapper {

    @Test
    public void testMapping() throws Exception {

        //SwissModel API: https://swissmodel.expasy.org/repository/uniprot/O94856.json?provider=swissmodel
        // TODO: find a better example
        UniprotToModelCoordinatesMapper mapper = new UniprotToModelCoordinatesMapper();
        mapper.setFrom(38);
        mapper.setTo(812);
        mapper.setAlignment(">O94856\n" +
                "TQPPTITKQSAKDHIVDPRDNILIECEAKGNPAPSFHWTR-NSRFFNIAKDPRVSMRRRSGTLVIDFRSG--GRPEEYEGEYQCFARNKFGTALSNRIRLQVSKSPLWPKENLDPVVVQEGAPLTLQCNPPPGLPS--PVIFWMSSSMEPIT----QDKRVSQGHNGDLYFSNVMLQDM-QTDYSCNARFHFTHTIQQK-NPFTLKVLTTRGVAERTPSFMYPQGTASSQMVLRGMDLLLECIASGVPTPDIAWYKKGGDLPSDK-----AKFENFNKALRITNVSEEDSGEYFCLASNKMGSIRHTISVRVKAAPYWLDEPKNLILAPGEDGRLVCRANGNPKPTVQWMVNGEPLQSAPPNPNREVAGDTIIFRDTQISSRAVYQCNTSNEHGYLLANAFVSVL--DVPPRMLSPRNQLIRVILYNRTRLDCPFFGSPIPTLRWFKNGQGSNLDGGNYHV----YENG----SLEIKMIRKEDQGIYTCVATNILGKAENQVRLEVKDPTRIYRMPEDQVARRGTTVQLECRVKHDPSLKLTVSWLKDDEPLYIGNRMKK-EDDSLTIFGVA-ERDQGSYTCVASTELD-QDLAKAYLTVLADQATPTNRLAALPKGRPDRPRDLELTDLAERSVRLTWIPGDANNSPITDYVVQFEEDQF--QPGVWHDHS-KYPGSVNSAVLRLSPYVNYQFRVIAINEVGSSHPSLPSERYRTSGAPPESNPGDVKGEGTRK----------NNMEITWTPMNATSAFGPNLRYIVKWRRRETREAWNNVTVWGSRYVVGQTPVYVPYEIRVQAENDFGKGPE\n" +
                ">3dmk.1.A\\QKGPVFLKEPTNRIDFSNSTGAEIECKASGNPMPEIIWIRSDGTAVGDV--PGLRQISSDGKLVFPPFRAEDYRQEVHAQVYACLARNQFGSIISRDVHVRAVVAQYYE-ADVNKEHVIRGNSAVIKCLIPSFVADFVEVVSWHTDEEENYFPGAEYDGKYLVLPSGELHIREVGPEDGYKS-YQCRTKHRLTGETRLSATKGRLVITE--PISSAVPKVVSL-AKFDMKTYSGSSTMALLCPAQGYPVPVFRWYKFIEGTTRKQAVVLNDRVKQVSGTLIIKDAVVEDSGKYLCVVNNSVGGESVETVLTVTAPLSAKIDPPTQTVDFGRPAVFTCQYTGNPIKTVSWMKDGKAIGH---------SESVLRIESVKKEDKGMYQCFVRNDRESAEASAELKLGGRFDPPVIRQAFQ-EETMEPGPSVFLKCVAGGNPTPEISWELDGKKIAN-NDRYQVGQYVTVNGDVVSYLNITSVHANDGGLYKCIAKSKVGVAEHSAKLNVYGLPYI-RQMEKKAIVAGETLIVTCPVAGYPI--DSIVWERDNRALPINRKQKVFPNGTLIIENVERNSDQATYTCVAKNQEGYSARGSLEVQVMVLPRIIP-----------FAFEEG--PAQVGQYLTLHCSVPGG-DLP---LNIDWTLDGQAISEDLGITTSRVGRRGSVLTIEAVEASHAGNFTCHARNLAGHQQFTTPLNV-YVPPR-WILEPTDKAFAQGSDAKVECKADGFPKPQVTWKKAV-----GDTPGEYKDLKK---S---DNIRVEEGTLHVDNIQKTNEGYYLCEAINGIGSGLS\n");
        mapper.setTemplate("3dmk.1.A");
        mapper.map();

//        assertEquals(-1, mapper.getModelCoordinateByUniprotPosition(38));
//        assertEquals(39, mapper.getModelCoordinateByUniprotPosition(39));
    }
}
